Finished project for assignment week 3
HackYourAssignment/Assignments-cohort47 pull request #12
Opened 2024-02-12 11:44 UTC by BenGumaan

2024-02-19 15:47 UTC, kasimoglou requested changes
Truly great work, well done!! There is a tiny bug in ex3 - I've left you a comment. Could you please adjust the code to fix it?

2024-02-19 15:47 UTC, kasimoglou commented on 1-JavaScript/Week3/assignment/ex1-doubleEvenNumbers.test.js
> +  return doubledNumbers;
Perfect! :raised_hands:

2024-02-19 15:47 UTC, kasimoglou commented on 1-JavaScript/Week3/assignment/ex2-mondaysWorth.test.js
> +  return `€${totalEarning}`;
Super, well done! :clap:

2024-02-19 15:47 UTC, kasimoglou commented on 1-JavaScript/Week3/assignment/ex3-lemonAllergy.test.js
> +    (fruit) => !fruit.includes(unwantedFruit)
Why did you choose to use `includes` here? What if you execute this function and `fruitbasket` is `['watermelon', 'apples']` and the unwanted fruit is `melon`? Will this run correctly?

2024-02-19 15:47 UTC, kasimoglou commented on 1-JavaScript/Week3/assignment/ex3-lemonAllergy.test.js
> +    expect(result).toStrictEqual(expected);
Here you could also check whether result doesn't include the unwanted fruit. How could you check that?

2024-02-19 15:47 UTC, kasimoglou commented on 1-JavaScript/Week3/assignment/ex4-observable/ex4-observable.js
> +      subscribers.forEach((subscriber) => subscriber(message));
Perfect! :100:

2024-02-19 15:47 UTC, kasimoglou commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +      )} from ${name} to ${wallet.getName()}`
Awesome! You found the bug and fixed it! :raised_hands:

2024-02-19 15:47 UTC, kasimoglou commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +    answer: 'c',
Everything looks perfect!

2024-02-20 16:33 UTC, BenGumaan commented on 1-JavaScript/Week3/assignment/ex3-lemonAllergy.test.js
> +    (fruit) => !fruit.includes(unwantedFruit)
Well, I chose to use `includes` in here because I thought it was going to be perfect to do so but didn't know that `includes` will return `TRUE` even if the target fruit name was part of another fruit name 😅. Thank you so much for pointing this out, it actually helped me learn something new and valuable.

2024-02-20 16:34 UTC, BenGumaan commented on 1-JavaScript/Week3/assignment/ex3-lemonAllergy.test.js
> +    expect(result).toStrictEqual(expected);
I could check that by doing this:

```
  test('should return a new array that does not include the unwanted fruit (lemon)', () => {
    const unwantedFruit = 'lemon';
    const result = sanitizeFruitBasket(fruitBasket, unwantedFruit);
    expect(result).not.toContain(unwantedFruit);
  });
```

2024-10-01 15:15 UTC, closed without merging