Mohammed_Gumaan_w1_browsers
HackYourAssignment/Assignments-cohort47 pull request #26
Opened 2024-02-26 22:56 UTC by BenGumaan

Finished project for assignment of week 1 of Browsers Module (ex1/2/3/4/5).

2024-03-04 18:49 UTC, imtiaz101325 requested changes
Great work so far! 😄 
I think that you have followed solid naming conventions. 👍🏾 

I think the only place you **have to** change stuff in the 5th assignment where you need to calculate the middle of the screen dynamically.

The rest are nice to haves but I'd strongly encourage you to at least think about them.

2024-03-04 18:49 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
Very nice use of variables! 🙌🏾

2024-03-04 18:49 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +  let currentLeft = parseInt(img.style.left);
Since `parseInt` can parse numbers other than decimals(hexadecimals for example). It's better to be explicit by passing in a second argument to the function that tells it what kind of number the first argument is. e.g. `parseInt(img.style.left, 10)`.

2024-03-04 18:49 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +  if (currentLeft === 500 ) {
Here `500px` maybe roughly the middle of your computer screen, it may not be the same for bigger or smaller screens. So please work on this condition a bit more and try to find out the "middle" of the screen using JS.

2024-03-16 21:14 UTC, BenGumaan commented on 2-Browsers/Week1/assignment/ex3-hijackLogo.js
> +  const google_logo = document.querySelector('.lnXdpd');
Well, as for the first question, why would Google name a class so? I actually have no clue and would love to know the reason behind it. 

I don't think this code will still work after a while. If the class name is changed, the code will break.

2024-03-16 21:41 UTC, BenGumaan commented on 2-Browsers/Week1/assignment/ex4-whatsTheTime/index.js
> +    const currentTime = new Date().toLocaleTimeString();
After a deep search, I arrived at the conclusion that I should specify the `options` parameter to enforce a specific format. 

For example, I could use this approach to ensures consistent and accurate time formatting:  
`const currentTime = new Date().toLocaleTimeString('en-US', { hour12: false });
`

Thank you so much for bringing this to my attention!

2024-03-17 19:14 UTC, imtiaz101325 approved these changes
Looks good to me! (Do checkout the solution for exercise 4 at other angles)

2024-03-17 19:14 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex4-whatsTheTime/index.js
> +    const currentTime = new Date().toLocaleTimeString('en-US', { hour12: false });
Interesting solution 😄

2024-10-01 15:15 UTC, closed without merging